seed: 40

env:
  max_steps: None
  eval_max_steps: 1000 #cant be more than 1200, otherwise trainning will be extremely slow
  scenario_name: "occt_scenario"
  scenario:
    enable_obs_audit: False
    viewer_zoom: 20.0
    resolution_factor: 4
    n_agents: 5
    task_class: 1
    is_rand_arc_pos: True
    mask_ref_vel: True
    cargo_half_width: 2
    threshold_near_other_agents_c2c_high: 6
    max_speed: 5.0
    init_vel_mean: 3.0
    init_vel_std: 1.0 # useless if is_rand_init_vel is False
    still_space: 6
    init_arc_pos: 0.0 # useless if is_rand_arc_pos is False
    use_center_frenet_ref: True # True means use continuous frenet reference, False means use discrete reference
    n_nearing_agents_observed: 2
    # reward weights
    reward_progress: 5.0
    reward_vel: 0
    reward_goal: 100
    reward_hinge: 200
    reward_track_hinge: 200
    reward_track_hinge_vel: 20
    reward_approach_hinge: 0
    reward_track_ref_vel: 20       
    reward_track_ref_space: 20
    reward_track_ref_heading: 10
    reward_track_ref_path: 50
    penalty_goal_incomplete_hinge: -100
    goal_incomplete_hinge_penalty_mode: scaled
    penalty_near_boundary: -200
    penalty_near_other_agents: -200
    penalty_change_steering: -0.0
    penalty_change_acc: -0.0
    penalty_collide_with_agents: -400
    penalty_outside_boundaries: -400
    penalty_backward: -400
  device: ??? # These values will be populated dynamically
  vmas_envs: 300

model:
  shared_parameters: True
  centralised_critic: True  # MAPPO if True, IPPO if False

collector:
  frames_per_batch: 60_000 # Frames sampled each sampling iteration
  n_iters: 500 # Number of sampling/training iterations
  total_frames: ???

buffer:
  memory_size: ???

loss:
  gamma: 0.99
  lmbda: 0.95
  entropy_eps: 0.05
  clip_epsilon: 0.2

train:
  num_epochs: 45  # optimization steps per batch of data collected
  minibatch_size: 4096 # size of minibatches used in each epoch
  lr: 5e-5
  max_grad_norm: 40.0
  device: ???
  resume_from_checkpoint: None # absolute path

eval:
  evaluation_interval: 10
  evaluation_episodes: 12

logger:
  backend: swanlab # Delete to remove logging
  project_name: "MAPPO_OCCT"
  group_name: "ours0316_baseline"
  resume_swanlab_id: None # copy from swanlab page
  mode: cloud
