seed: 0

env:
  max_steps: 200
  scenario_name: "occt_scenario"
  scenario:
    n_agents: 3
    task_class: 0
    platoon_vel_mean: 7.0
    platoon_vel_var: 4.0
    is_observe_distance_to_boundaries: False # False means observe future left and right boundaries
  device: ??? # These values will be populated dynamically
  vmas_envs: ???

model:
  shared_parameters: True
  centralised_critic: True  # MAPPO if True, IPPO if False

collector:
  frames_per_batch: 60_000 # Frames sampled each sampling iteration
  n_iters: 500 # Number of sampling/training iterations
  total_frames: ???

buffer:
  memory_size: ???

loss:
  gamma: 0.9
  lmbda: 0.9
  entropy_eps: 0
  clip_epsilon: 0.2

train:
  num_epochs: 45  # optimization steps per batch of data collected
  minibatch_size: 4096 # size of minibatches used in each epoch
  lr: 5e-5
  max_grad_norm: 40.0
  device: ???
  resume_from_checkpoint: None

eval:
  evaluation_interval: 10
  evaluation_episodes: 200

logger:
  backend: swanlab # Delete to remove logging
  project_name: occt
  group_name: mlp
